name: Imogen LV2 build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:

  LV2-build:
  
    name: Build
    runs-on: Ubuntu-latest
    timeout-minutes: 60
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen
        
    - name: Run build script
      shell: bash
      run: cd $GITHUB_WORKSPACE/imogen/scripts && bash build_LV2.sh
